title: iii-earth.id
default_lang: en
author:
  name: Yuvensianti
  email: info@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Hidup Sehat & Sukses Bersama THREE'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
